### ISSUE TITLE
PDF output

### ISSUE THREAD

**Issue by under-score** [lschmelzeisen/nasty#11]
works as expected, great. I just wonder what is the easiest way to get a pdf from the json file that includes all attached pictures?

**Comment by lschmelzeisen** [comment]
Not sure what you mean exactly. Out of which JSON do you want to create a PDF? What do you expect the PDF to contain? Do you have any example input/output?

In any case, this definitely sounds out-of-scope for this project. So I'm afraid, I can't help you with that.

**Comment by under-score** [comment]
Archiving a Twitter thread directly from the browser isn't an easy task. 
Nasty spits out a JSON output of a full thread so I wonder how this can be easily converted into HTML or PDF without writing an own parser?

**Comment by lschmelzeisen** [comment]
Ah, so you want to render a Tweet's JSON into something human readable? For my purposes, it was always sufficient to look at the `full_text` attribute of the JSON since I usually only care about the text. Rendering the full Tweet becomes pretty complicated very fast, when you consider that nowadays a Tweet can carry multiple different media objects (Retweets, Images/Videos, etc.). Something like this probably exists somewhere, but on the top of my head, sadly can't point you in any direction.

**Comment by under-score** [comment]
thank you!
