### ISSUE TITLE
No response using thread/replies-commands for Tweet-ID

### ISSUE THREAD

**Issue by isspek** [lschmelzeisen/nasty#3]
Hi @lschmelzeisen,

Thank you for this work.

I try to read the [following tweet](https://twitter.com/ipekbrs/status/1230464833696432129) with the command

```
nasty thread --tweet-id 1230464833696432129
```

NASTY gives the following response:

```
2020-02-20 16:14:38,186 I [ nasty._retriever.retriever      ] Received 3 consecutive empty batches.
```

I also tried the example in README. But that one gave a json response.

What could be the problem of  the [Tweet](https://twitter.com/ipekbrs/status/1230464833696432129) ?

Thanks in advance!

**Comment by lschmelzeisen** [comment]
That is working as I intended it to, but probably not as you expected (:

The `thread`-command assumes that you do not care about the Tweet whose ID you are supplying but rather only about Tweets that are threaded under it.

For example, for [this Tweet](https://twitter.com/fchollet/status/1230611916701229064) you would "only" get the following Tweets as results:
- [The finance industry has a saying for this: "past performance is no guarantee of future results". Your model scoring X on your test dataset doesn't mean it will perform at level X on the next N situations it encounters in the real world. The future may not be like the past.](https://twitter.com/fchollet/status/1230612366494035968)
- [So when asking the question, "would you rather use a model that was evaluated as 90% accurate, or a human that was evaluated as 80% accurate", the answer depends on whether your data is typical per the evaluation process. Humans are adaptable, models are not.](https://twitter.com/fchollet/status/1230612972210282496)
- [If significant uncertainty is involved, go with the human. They may have inferior pattern recognition capabilities (versus models trained on enormous amounts of data), but they understand what they do, they can reason about it, and they can improvise when faced with novelty](https://twitter.com/fchollet/status/1230613828301254657)
- [If every possible situation is known and you want to prioritize scalability and cost-reduction, go with the model. Models exist to encode and operationalize human cognition in well-understood situations.](https://twitter.com/fchollet/status/1230614605325455360)
- [("well understood" meaning either that it can be explicitly described by a programmer, or that you can amass a dataset that densely samples the distribution of possible situations -- which must be static)](https://twitter.com/fchollet/status/1230614606164316161)

Alternatively there is the `replies`-command which gives you all top-level replies to a Tweet (but again, not the Tweet itself). For example I replied to your test-Tweet and now returns just my Tweet.

```
nasty replies --tweet-id 1230464833696432129
```

There currently is no way in NASTY to get the full text (and other data) about a specific Tweet given its Tweet-ID. This is somewhat intentional as [the official Twitter-API provides amble capability here](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-lookup)
I always use it with from Python with [TweePy](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-lookup)

I don't want NASTY to become a way to circumvent the Twitter-API but just to provide functionality that is not available in it.
